### ISSUE TITLE
Usability suggestion for priority displaying of locked files

### ISSUE THREAD

**Issue by Impulse87** [Noxdew/git-locks-manager#144]
Very cool tool!

**Issue:**
Currently i have to search/filter for files i want to work on, in order to see if they are locked or not

**Solution/Mitigation**
In order to make it obvious for users which files are currently locked, it would be good to have locked files sorted at the top by default. And/Or a filter option to only show locked files.

**Considered Alternatives**
Maybe a split view, with two lanes. One with unlocked files, one with locked files. Or a Scroll bar shown with colored highlights where locked files are situated in the list.

**Additional Context**
This tool is already a huge help, and more then workable as is.

**Comment by morwoen** [comment]
Hey @Impulse87, Thanks for taking the time to leave feedback, it is much appreciated!

Your suggestion makes total sense. I will try to find some time to implement it :)

**Comment by Impulse87** [comment]
noice already implemented, thank you very much! 💯

**Comment by morwoen** [comment]
Thanks again for your feedback :)
