### ISSUE TITLE
Default export of Attribute Configuration adds characters which cause read-only property to fail.

### ISSUE THREAD

**Issue by OfficialKris** [Noxdew/git-locks-manager#146]
I was trying to setup a MVP test repo and was getting inconsistent behavior with git refusing to set certain files to read-only. Turns out the tab character (U+0009) present in the default .gitattributes was causing this. Replacing the tab character in .gitattributes with a single space fixed the problem.

This was a small issue but had me worried that I wouldn't be able to use this tool. Now I can!

Please provide the following information:

**Operating system**:  Windows 11 23H2 and WSL 2.1.5.0 with kernal version 5.15.146.1-2
**Version of the template**: v1.0.5

To replicate:

```
mkdir test
cd test
git init
git lfs install
touch example.png
```

Add remote to git repo
Open Git Locks Manager
Add git repo to Git Locks Manager
Configure Repository -> Configure Git Attributes -> Apply Default Configuration

```
git add .
git commit -m "Initial commit"
git push
```

Observe that example.png does not have read only property
Replace ``` *.png	filter=lfs diff=lfs merge=lfs -text lockable```
with ```*.png filter=lfs diff=lfs merge=lfs -text lockable```

```
git add .
git commit -m "Changes"
git push
git checkout .
```

Observe that example.png includes read only property

**Comment by morwoen** [comment]
Hey Kris, thanks for reporting this issue. I'm glad you managed to figure out a workaround!

It is very weird that the lfs docs do specify any whitespace as the delimiter between those sections so this could be something else playing around 🤔 

I'll give it a shot at reproducing and see what the best course of action is.

**Comment by morwoen** [comment]
Hey, which version of Git are you using?

**Comment by morwoen** [comment]
Thanks for that. To give you some context I'm using a package ([this one](https://www.npmjs.com/package/git-attributes)) to parse and serialise back the git attributes file which makes it difficult to just swap between the spaces and tabs.

I am currently investigating if this is a problem with LFS in general and/or if there is a git attributes parser/serialiser that works better that I can switch to.

**Comment by morwoen** [comment]
Quick update, I've created a PR to the library I mentioned above to allow Git Locks Manager to configure this behaviour. Since you were able to unblock yourself I will wait for a little bit to see if the maintainer is active and if they will merge and release this change. If not I will look to alternative ways to fix this. Thanks for your patience and I hope the tool is helpful despite this issue :)

**Comment by morwoen** [comment]
Hey, there was some complication in releasing an update as there are a lot of incompatibilities with newer version of the dependencies. I merged a change to address the issue raised, however, I am just confirming the CI build can work as intended before releasing it as latest
