### ISSUE TITLE
Force unlock

### ISSUE THREAD

**Issue by ttermeer-reboundcg** [Noxdew/git-locks-manager#148]
Would it be possible to add support for force unlock?

**Comment by morwoen** [comment]
Thanks for the suggestion, that's definitely something fitting for the application. I might be able to add it later this month/next month

**Comment by morwoen** [comment]
Version 2.0.0 is being released which has this implemented inside. The node 20 upgrade had to happen before any other change so many things changed underneath, if you notice any bugs please report them :)

**Comment by morwoen** [comment]
For more context, once you try unlocking a file locked by another person, upon failure a new button for force unlocking the file will appear
