### ISSUE TITLE
Fails to understand and appropriate map submodules

### ISSUE THREAD

**Issue by skyphyr** [Noxdew/git-locks-manager#149]
In a git repository which uses submodules, git-locks-manager appears to be going upwards from the selected directory until it finds the main repository root (presumably looking for the .git directory, failing to either notice or to correctly process the .git file that exists within submodule directories; this file contains a path to the submodule's repository storage data, typically of the form gitdir: ../.git/modules/${SubmoduleName}).

As a result of this, once it finds the main root and then searches for all lfs files, it only populates those in the main subdirectory, treating all lfs files within the submodules as if they don't exist, and as such they never appear in order to be locked or unlocked.

**Comment by morwoen** [comment]
Hey, thanks for reporting this. The app uses `git ls-files` [here](https://github.com/Noxdew/git-locks-manager/blob/main/app/electron/git.js#L158) and there is a flag `--recurse-submodules` that can be added there that will likely fix the issue, however, there are some issues that mean I can't test this locally before releasing it so while small this might need to wait a little while I fix those issues.

In the mean time I believe the issue can be worked around in a similar fashion to the way GitHub Desktop handles submodules. You should be able to add the submodules as individual repos and handle file locking that way. I appreciate that it isn't all on a single view and will require more navigation but it should get you going while I fix thing up :)

**Comment by morwoen** [comment]
Version 2.0.0 is being released which has this implemented inside. The node 20 upgrade had to happen before any other change so many things changed underneath, if you notice any bugs please report them :)
