### ISSUE TITLE
Unable to add new repository

### ISSUE THREAD

**Issue by tyen901** [Noxdew/git-locks-manager#151]
**Operating system**:  Win 10 Pro
**Version**:  2.0.0

I have installed version Git Locks Manager 2.0.0 for the first time on my machine. I am unable to add any repository I have locally to it.
The error toast message pops up with "The folder was not identified as Git Repository"

**Comment by morwoen** [comment]
Hey, thanks for reaching out. I am able to add new ones locally, so lets dig a little deeper into your setup to see why this is happening.

What is the name of the remote in your git repository? You can check that by running `git remote -v` in the same folder you're trying to add. Currently Git Locks Manager is set to look for `origin` explicitly as this is the default Git sets when you clone a new repo. Here is my output:
```
origin  https://github.com/Noxdew/git-locks-manager.git (fetch)
origin  https://github.com/Noxdew/git-locks-manager.git (push)
```

**Comment by tyen901** [comment]
I cloned this repo and I get the same result for the command.
```
PS D:\git-locks-manager> git remote -v
origin  https://github.com/Noxdew/git-locks-manager.git (fetch)
origin  https://github.com/Noxdew/git-locks-manager.git (push)
```

I did not have any further luck after a clean uninstall of the application and deletion of all the temporary files and folders that were created. I also tried a reboot.

**Comment by morwoen** [comment]
Do you get the same error if you try adding the cloned git-locks-manager as well? My concern is that maybe your other repository is set up differently.

Another thing you can try is running `git config --get remote.origin.url` in your repository folder. That is the specific command Git Locks Manager uses to get the repo url.

**Comment by tyen901** [comment]
Yes I am unable to add any repository.

Using `git config --get remote.origin.url` returns this.

```
PS D:\git\git-locks-manager> git config --get remote.origin.url
https://github.com/Noxdew/git-locks-manager.git
```

**Comment by morwoen** [comment]
That's very curious. Could you try opening a cmd, navigate to the Git Locks Manager install folder and run the exe through cmd. That will allow you to see the logs. Could you share what you get once you try adding a repository? I am hoping that would tell us what is going wrong 🤞

**Comment by tyen901** [comment]
No new lines appeared when trying to add the repositories.
```
PS C:\Users\Tyen\AppData\Local\Programs\git-locks-manager> & '.\Git Locks Manager.exe'
PS C:\Users\Tyen\AppData\Local\Programs\git-locks-manager>
Checking for update
[secure-electron-store:renderer]=> initialized store. Data file: 'C:\Users\Tyen\AppData\Roaming\git-locks-manager\data.json'.
[secure-electron-store:main]=> did not find unprotected data file when trying read 'C:\Users\Tyen\AppData\Roaming\git-locks-manager\unprotected.json'. Creating an empty data file.
Stored Config {}
Generated new staging user ID: f22b87f2-de91-51a1-83c8-a255e5ff5f0b
[secure-electron-store:main]=> wrote "'theme':'auto'" to file 'C:\Users\Tyen\AppData\Roaming\git-locks-manager\unprotected.json'.
[secure-electron-store:main]=> wrote "'theme':'auto'" to file 'C:\Users\Tyen\AppData\Roaming\git-locks-manager\unprotected.json'.
[secure-electron-store:main]=> received a request to read from the key 'repos' from the given file 'C:\Users\Tyen\AppData\Roaming\git-locks-manager\data.json'.
[secure-electron-store:main]=> wrote "'locale':'en'" to file 'C:\Users\Tyen\AppData\Roaming\git-locks-manager\unprotected.json'.
[secure-electron-store:main]=> read the key 'repos' from file => 'undefined'.
Update for version 2.0.0 is not available (latest version: 2.0.0, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
```

**Comment by morwoen** [comment]
I think I finally managed to reproduce it locally. I hope to have a fix soon!

**Comment by morwoen** [comment]
It looks like a change in the store when I upgraded Node in v2 caused this. I will publish 2.0.1 this afternoon. Thanks a lot for reporting and bearing with me while I fix it. I hope you find the app useful :)

**Comment by tyen901** [comment]
I can confirm the 2.0.1 release has fixed it on my end :)
