### ISSUE TITLE
Feature Request: Batch select and unlock files

### ISSUE THREAD

**Issue by tyen901** [Noxdew/git-locks-manager#153]
**Is your feature request related to a problem? Please describe.**
I often have dozens of small files I need to unlock. It's slow to click on each one individually.

**Describe the solution you'd like**
I'd like to be able to click one item, then click another while holding the shift key and it would select them all. Then I'd like to click a unlock button to unlock them all.
I would also like to be able to 'add' to the selection by using the ctrl key and individually clicking on each item I want included in the batch process.

**Describe alternatives you've considered**
The git client 'Fork' has a implementation of this. However it doesn't allow for force unlocking.

**Comment by morwoen** [comment]
Thanks so much for the suggestion. I feel it can be tricky with force-unlocking a lot of files as it can be dangerous.

I wouldn't expect having to force-unlock often. Is that something that is part of your workflow? Might be helpful if you can share more about it?

If it is more of a one-time thing writing a short script might help you force-unlock the files quickly and then return to the normal workflow.

I still appreciate the idea of batch selection and think it should be part of the app, however, I can't commit to when I'll have the time to implement it.

**Comment by tyen901** [comment]
Unlocking many files is something I have to do very often. Our team is a mix of designers and artists, not all of whom are comfortable with git or the command line. Also our timezones are spread out don't cross over. Often I need to quickly unlock many of their files.

In the meanwhile I am able to use ```git lfs locks``` to get the file paths and edit the lines in order to prefix them with `git lfs unlock`. This solves the problem for now.

**Comment by morwoen** [comment]
Thanks again for your feature suggestion. I've implementing something that should mostly solve your use case. The only limitation is that force-unlocking isn't possible through the batch selection. I think this can be a fairly destructive feature so having the additional layer can he helpful for more inexperienced users. Hope you find it useful :)
