### ISSUE TITLE
Issue: Application is slow to read very large repositories due to it displaying 'All Files'

### ISSUE THREAD

**Issue by tyen901** [Noxdew/git-locks-manager#154]
Please provide the following information:

**Operating system**:  Win 10
**Version of the template**: 2.0.1

The application is very slow when loading up my repository which contains around 20,000 files. The Git Unlock Manager defaults to showing 'All Files' and appears to be quite slow to update the list of files. 
It would be preferred if it defaulted to only showing the currently locked files.

**Comment by morwoen** [comment]
Thanks for reporting this. I can see how this can be annoying and it can definitely be changed to avoid refreshing all files all the time. I will likely have time to sort this towards the end of the month :)

**Comment by morwoen** [comment]
Hey, I finally got around to implementing this. Locking and unlocking should happen locally, with only the new lock being fetched when locking a file. That should significantly speed up the process. The files list will only be refreshed if you manually click the button.
